language: python
python:
- 2.7
- 3.5
env:
- DJANGO="Django>=1.8,<1.9"
- DJANGO="Django>=1.9,<1.10"
- DJANGO="Django>=1.10,<1.11"
install:
- pip install -q $DJANGO coveralls
script:
- coverage run --source=axes runtests.py
- coverage report
after_success:
- coveralls
deploy:
  provider: pypi
  user: jazzband
  distributions: sdist bdist_wheel
  password:
    secure: jFsQCmQ2ih3FNatGSxQ5cRwLgXFLPReJw2+GeBLK4nkL2zr6z6PM5j74pVk8cS5uKrxNhunrwZBeamG+N4J0TnYCKKJxP8hQIRQ96N8n/YL5ycm6XnPALpfhHXXcfoBeqZQCoeueKOMswBY+0eOJv+7Bj/O0GgSOeQC2/1CNhZk=
  on:
    tags: true
    repo: jazzband/django-axes
    condition: $DJANGO = "Django>=1.8,<1.9"
    python: '2.7'
